version: 2

jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install postgresql-client

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:structure:load

      - run:
          name: Parallel RSpec
          command: bin/rails test

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results

dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install pdftk

machine:
  ruby:
    version:
      2.4.1

  environment:
    HELP_EMAIL: help@technovationchallenge.org
    ADMIN_EMAIL: info@technovationchallenge.org
    PDFTK_PATH: /usr/bin/pdftk
    AIRBRAKE_PROJECT_ID: n-a
    AIRBRAKE_PROJECT_KEY: n-a
    NEW_RELIC_LICENSE_KEY: no-matter
    GOOGLE_MAPS_API_KEY: no-matter-in-test
    HOST_DOMAIN: localhost:3000
    AWS_BUCKET_NAME: technovation-attachments-test
    CAMPAIGN_MONITOR_API_KEY: no-matter-in-test
    STUDENT_LIST_ID: no-matter-in-test
    MENTOR_LIST_ID: no-matter-in-test
    JUDGE_LIST_ID: no-matter-in-test
    REGIONAL_AMBASSADOR_LIST_ID: no-matter-in-test
    PARENT_LIST_ID: no-matter-in-test
    REDIS_URL: redis://127.0.0.1:6379/0
    BONSAI_URL: localhost:9200
    GOOGLE_TIMEZONE_API_KEY: no-matter-in-test
    BING_MAPS_API_KEY: no-matter-in-test
    ENABLE_RA_SCORES: yes
    SEARCH_INDEX_TIMING: realtime
    RA_SLACK_URL: no-matter-in-test
    MENTOR_SLACK_SIGNUP_URL: no-matter-in-test
    STUDENT_SLACK_SIGNUP_URL: no-matter-in-test

general:
  branches:
    ignore:
      - /.*-stable/
      - master

deployment:
  beta:
    branch: ra-ui
    heroku:
      appname: tc-2018

  qa:
    branch: qa
    heroku:
      appname: technovation-qa

  prod:
    branch: production
    heroku:
      appname: technovation
